### ISSUE TITLE
Shader model 3 must be supported"

### ISSUE THREAD

**Issue by fantaandcode** [johnramsden/pathofexile-flatpak#5]
Just installed this in 18.04, I get a wine program crash, saying "Internal errors - invalid parameters received" In the actual wine session, there's an exception, saying "Shader model 3 must be supported"
I'm running Ubuntu 18.04 with bumblebee and nvidia-driver-390.

Here are some [screenshots](https://imgur.com/a/VJWke2u) of the errors. This is the [output](https://pastebin.com/eGqEzSGL) from the terminal when running it. Here's the [log file](https://www.dropbox.com/s/grq6d9j8rdunnh8/log?dl=0) created the trace. WARNING! Very large file size, over 160 MB, I can't really open it on Sublime without it lagging out and eventually freezing. Even opening it in a terminal with cat takes a while for it to load. Here is my system specs:

Intel i5-6300HQ
Ubuntu 18.04 LTS
16 GB of DDR3L 1600MHz RAM
NVIDIA GeForce GTX 960M 4GB GDDR5
256GB SSD and 1TB 7200 RPM HDD

These are some of the [steps and processes](https://github.com/Bumblebee-Project/Bumblebee/issues/951) I used to get Ubuntu running on my laptop with nvidia 390 drivers, because Dell 7559s are pretty annoying with Optimus.

---
### Files

[log](https://github.com/johnramsden/pathofexile-flatpak/files/1973339/log.zip)

![poe_exception2](https://user-images.githubusercontent.com/8735102/39614107-ead54b12-4f21-11e8-879f-894a5a0443bc.png)
![poe_exception1](https://user-images.githubusercontent.com/8735102/39614108-eaee5332-4f21-11e8-9151-799be990ae6a.png)

**Comment by johnramsden** [comment]
[Apparently](https://askubuntu.com/questions/669011/what-is-the-difference-between-optirun-and-primusrun) there can be problems related to optimus with wine.

Also, when the flatpak, are you running it with optirun?

```
optirun flatpak run ca.johnramsden.pathofexile
```

Do you think you'd be able to try disabling Bumblebee, and see if it runs using just the dedicated graphics card?

**Comment by fantaandcode** [comment]
Uhh... I wouldn't know how to do that. But I'm not running it with optirun since in prime-select, I'm using the Nvidia profile anyway and not the Intel profile. I'll try reinstalling and see if there's any difference with using different drivers and if it's specifically due to the 390 drivers.

**Comment by johnramsden** [comment]
So you're using the dedicated graphics card by default?

I don't know if you should go to all the trouble of reinstalling unless it's already a freshly installed system... I'll keep looking into it and see if I can find some more information though.

What might also help to get a bit more information related to wine would be running with debugging enabled. It's going to be very slow and spit out a lot of data but if you wait it should eventually start up.

```
flatpak run --env=WINEDEBUG=all ca.johnramsden.pathofexile > winedebug.log
```

If you put it in a zip file you should be able to attach it directly to this issue.

**Comment by fantaandcode** [comment]
I'm not sure what happened. But it's working again. Though I'm using Xubuntu 18.04 and installed the driver through their own driver management thing. I think that this may be more a problem with Bumblebee than anything else. So I'm just going to close this for now.

**Comment by 0xjon0** [comment]
It isn't a bumblebee issue.  I'm having the same problem on a fresh install of Mint Tara w/Cinnamon without bumblebee.   AMD CPU & graphics (using the default drivers) that otherwise run 3d games well.

It feels more like a driver/DX issue to me but I'm unable to update my video drivers for a few days.  Was unable to provide the debug output you requested because everything I tried just output 'Can't attach process 002e: error 5' or similar without anything helpful.
